### ISSUE TITLE
Add envs option in StepConfig

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#13]
It would be awesome to set environment variable in each step

From:

```yml
steps:
  test-e2e-local-inmemory:
      run:
        - docker-compose up -d
        - export END2END_TEST=True; export REPOSITORY_MODE=inmemory; pytest -m end2end --variables tests/end2end/envs/local.yml
        - docker-compose down
  test-e2e-local-sqlite:
      run:
        - docker-compose up -d
        - export END2END_TEST=True; export REPOSITORY_MODE=sqlite; pytest -m end2end --variables tests/end2end/envs/local.yml
        - docker-compose down
```

to something like the following:

```yml
steps:
  test-e2e-local-inmemory:
      envs:
        END2END_TEST: True
        REPOSITORY_MODE: inmemory
      run:
        - docker-compose up -d
        - pytest -m end2end --variables tests/end2end/envs/local.yml
        - docker-compose down
   test-e2e-local-sqlite:
      envs:
        END2END_TEST: True
        REPOSITORY_MODE: sqlite
      run:
        - docker-compose up -d
        - pytest -m end2end --variables tests/end2end/envs/local.yml
        - docker-compose down
```
