### ISSUE TITLE
Add setup_detach option to StepConfig

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#17]
```yml
test-local:
    setup_detach:
      log_file: taskmanager.log
      run: python -m taskmanager
    run: pytest -m end2end
    teardown: rm taskmanager.log
```

Teardown should kill setup detach command
