### ISSUE TITLE
Add wait option on StepConfig

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#22]
It'd be nice to have a `wait` and `wait_for_http_200` option to control when the run starts

```yml
my-step:
  wait: 10 # seconds
  run: pytest
```

```yml
my-step:
  wait_for_http_200: http://0.0.0.0:8080/taskmanager
  run: pytest
```
