### ISSUE TITLE
Add option to config a StepConfig envvars with a filename 

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#26]
```yml
steps:
  envs-file-example:
    envs_file: examples/env.yml
    run:
      - echo "${MY_MANAGER}"
      - echo "${LUME_CONFIG_FILENAME}"
```
