### ISSUE TITLE
Not handled when something fails in setup

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#29]
```yml
test-e2e-local:
    envs:
      END2END_TEST: True
    envs_file: env.local.mysql.yml
    setup: docker-compose up -d
    wait_http_200: http://0.0.0.0:8080/taskmanager/healthcheck
    run: pytest -c pytest.end2end.ini --variables tests/end2end/envs/local.yml
    teardown:
      - docker-compose down
      - docker-compose ps
```

If something fails executing `docker-compose up -d` is not handled.
