### ISSUE TITLE
Add option to run specific commands depending on the operative system

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#31]
# First approach

## Install

```
install:
  run_ubuntu:
    - sudo apt update
    - sudo apt install myprogram
  run_macos:
    - brew install myprogram
  run:
    - echo "Hello"
```

##  Steps

```
clean:
  run_ubuntu:
    - sudo apt update
    - sudo apt install myprogram
  run_macos:
    - brew install myprogram
  run:
    - echo "Hello"
```

We should implement it  respecting the definition order of the runs.

**Comment by acostapazo** [comment]
I'd prefer the one proposed by @fgsalomon 

```yml

install:
  run:
    ubuntu:
       - sudo apt update
       - sudo apt install myprogram
     macos:
       - brew install myprogram
     all:
      - echo "Hello"
```
