### ISSUE TITLE
Global env configuration

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/lume#40]
Imagine a lume file which use several times the same envs on every steps

```yaml
name: lume-sample

install:
  run: echo "Installing..."

steps:
  step-1:
    envs:
      MY_ENV_1: 2
      MY_ENV_2: 0.2
    run: echo "Step 1"
  step-2:
    envs:
      MY_ENV_1: 2
      MY_ENV_2: 0.2
    run: echo "Step 2"
  step-3:
    envs:
      MY_ENV_1: 2
      MY_ENV_2: 0.2
    run: echo "Step 2"
```

Should be nice to configure common envs as global. Something like that:

```yaml
name: lume-sample

install:
  run: echo "Installing..."

envs:
  MY_ENV_1: 2
  MY_ENV_2: 0.2

steps:
  step-1:
    run: echo "Step 1"
  step-2:
    run: echo "Step 2"
  step-3:
    run: echo "Step 2"
```
